<?php

use App\Models\Business;use App\Models\Location;use App\Models\Permission;use App\Models\Role;use App\Models\User;use Database\Seeders\PermissionSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Laravel\Sanctum\Sanctum;
uses(RefreshDatabase::class);beforeEach(fn()=>$this->seed(PermissionSeeder::class));
function otContext():array{$b=Business::create(['name'=>'Transfer','currency'=>'EUR','timezone'=>'Europe/Berlin','status'=>'active']);$l=Location::create(['business_id'=>$b->id,'name'=>'Main','code'=>'MAIN','type'=>'bar','is_active'=>true]);$u=User::create(['name'=>'Manager','email'=>Str::random(8).'@test.dev','password'=>bcrypt('password')]);$r=Role::create(['business_id'=>$b->id,'name'=>'Manager','slug'=>'transfer-'.Str::random(5),'is_system'=>false]);$r->permissions()->sync(Permission::where('key','orders.update')->pluck('id'));$u->businesses()->attach($b->id,['role_id'=>$r->id,'status'=>'active']);Sanctum::actingAs($u);return[$b,$l,$u,['X-Business-Id'=>$b->id]];}
function otProduct(Business $b,string $name,string $price):string{$id=(string)Str::ulid();DB::table('products')->insert(['id'=>$id,'business_id'=>$b->id,'name'=>$name,'sale_price'=>$price,'tax_rate'=>'0.0000','is_active'=>true,'tracks_stock'=>false,'created_at'=>now(),'updated_at'=>now()]);return$id;}
function otOrder(Business $b,Location $l,User $u,array $lines,string $status='open'):array{$oid=(string)Str::ulid();$total='0.0000';foreach($lines as $x)$total=bcadd($total,$x[1],4);DB::table('orders')->insert(['id'=>$oid,'business_id'=>$b->id,'location_id'=>$l->id,'opened_by_user_id'=>$u->id,'number'=>'TR-'.Str::random(8),'type'=>'takeaway','status'=>$status,'currency'=>'EUR','subtotal'=>$total,'discount_total'=>'0.0000','tax_total'=>'0.0000','grand_total'=>$total,'opened_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$ids=[];foreach($lines as[$pid,$price]){$id=(string)Str::ulid();$ids[]=$id;DB::table('order_items')->insert(['id'=>$id,'business_id'=>$b->id,'order_id'=>$oid,'product_id'=>$pid,'product_name_snapshot'=>'Item','quantity'=>'1.0000','unit_price'=>$price,'tax_rate'=>'0.0000','line_subtotal'=>$price,'line_tax'=>'0.0000','line_total'=>$price,'preparation_status'=>'pending','created_at'=>now(),'updated_at'=>now()]);}return[$oid,$ids];}

test('split moves exact items and conserves financial total with immutable audit',function(){[$b,$l,$u,$h]=otContext();$a=otProduct($b,'A','10.0000');$c=otProduct($b,'C','5.0000');[$o,$items]=otOrder($b,$l,$u,[[$a,'10.0000'],[$c,'5.0000']]);$res=$this->postJson("/api/v1/orders/$o/split",['item_ids'=>[$items[1]],'reason'=>'Guests requested separate orders'],$h)->assertCreated();$dest=$res->json('data.destination.id');expect($res->json('data.source.grand_total'))->toBe('10.0000')->and($res->json('data.destination.grand_total'))->toBe('5.0000');expect(DB::table('order_items')->where('id',$items[1])->value('order_id'))->toBe($dest);$audit=DB::table('order_transfer_audits')->first();expect($audit->operation)->toBe('split')->and($audit->total_before)->toBe('15.0000')->and($audit->source_total_after)->toBe('10.0000')->and($audit->destination_total_after)->toBe('5.0000');});

test('split cannot move every active item or foreign item',function(){[$b,$l,$u,$h]=otContext();$p=otProduct($b,'A','10.0000');[$o,$items]=otOrder($b,$l,$u,[[$p,'10.0000']]);$this->postJson("/api/v1/orders/$o/split",['item_ids'=>$items,'reason'=>'Invalid full split'],$h)->assertStatus(422);$foreign=Business::create(['name'=>'Other','currency'=>'EUR','timezone'=>'UTC','status'=>'active']);$fl=Location::create(['business_id'=>$foreign->id,'name'=>'F','code'=>'F','type'=>'bar','is_active'=>true]);$fu=User::create(['name'=>'F','email'=>Str::random(8).'@f.dev','password'=>bcrypt('x')]);$fp=otProduct($foreign,'F','3.0000');[, $foreignItems]=otOrder($foreign,$fl,$fu,[[$fp,'3.0000']]);$this->postJson("/api/v1/orders/$o/split",['item_ids'=>[$foreignItems[0]],'reason'=>'Cross tenant attempt'],$h)->assertStatus(422);});

test('merge conserves total closes source and moves active items once',function(){[$b,$l,$u,$h]=otContext();$a=otProduct($b,'A','10.0000');$c=otProduct($b,'C','5.0000');[$dest]=otOrder($b,$l,$u,[[$a,'10.0000']]);[$source,$sourceItems]=otOrder($b,$l,$u,[[$c,'5.0000']]);$this->postJson("/api/v1/orders/$dest/merge",['source_order_id'=>$source,'reason'=>'Guests joined one bill'],$h)->assertOk()->assertJsonPath('data.grand_total','15.0000');expect(DB::table('orders')->where('id',$source)->value('status'))->toBe('closed')->and(DB::table('orders')->where('id',$source)->value('grand_total'))->toBe('0.0000');expect(DB::table('order_items')->where('id',$sourceItems[0])->value('order_id'))->toBe($dest);expect(DB::table('order_transfer_audits')->where('operation','merge')->count())->toBe(1);});

test('merge rejects cross location cross tenant self and payment started orders',function(){[$b,$l,$u,$h]=otContext();$p=otProduct($b,'A','10.0000');[$dest]=otOrder($b,$l,$u,[[$p,'10.0000']]);$this->postJson("/api/v1/orders/$dest/merge",['source_order_id'=>$dest,'reason'=>'Self merge invalid'],$h)->assertStatus(422);$l2=Location::create(['business_id'=>$b->id,'name'=>'Other','code'=>'O','type'=>'bar','is_active'=>true]);[$source]=otOrder($b,$l2,$u,[[$p,'10.0000']]);$this->postJson("/api/v1/orders/$dest/merge",['source_order_id'=>$source,'reason'=>'Cross location invalid'],$h)->assertStatus(422);$foreign=Business::create(['name'=>'Foreign','currency'=>'EUR','timezone'=>'UTC','status'=>'active']);$fl=Location::create(['business_id'=>$foreign->id,'name'=>'F','code'=>'F','type'=>'bar','is_active'=>true]);$fu=User::create(['name'=>'F','email'=>Str::random(8).'@z.dev','password'=>bcrypt('x')]);$fp=otProduct($foreign,'F','2.0000');[$fo]=otOrder($foreign,$fl,$fu,[[$fp,'2.0000']]);$this->postJson("/api/v1/orders/$dest/merge",['source_order_id'=>$fo,'reason'=>'Cross tenant invalid'],$h)->assertNotFound();[$paid]=otOrder($b,$l,$u,[[$p,'10.0000']],'payment_due');DB::table('payments')->insert(['id'=>(string)Str::ulid(),'business_id'=>$b->id,'order_id'=>$paid,'collected_by_user_id'=>$u->id,'method'=>'card','status'=>'completed','amount'=>'1.0000','currency'=>'EUR','amount_base'=>'1.0000','base_currency'=>'EUR','exchange_rate'=>'1.0000000000','idempotency_key'=>'tr-'.Str::uuid(),'paid_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$this->postJson("/api/v1/orders/$dest/merge",['source_order_id'=>$paid,'reason'=>'Paid source invalid'],$h)->assertStatus(422);});

test('discounted orders are blocked so split merge never silently reallocates discount',function(){[$b,$l,$u,$h]=otContext();$p=otProduct($b,'A','10.0000');[$a,$items]=otOrder($b,$l,$u,[[$p,'10.0000'],[$p,'10.0000']]);DB::table('orders')->where('id',$a)->update(['discount_total'=>'2.0000','grand_total'=>'18.0000']);$this->postJson("/api/v1/orders/$a/split",['item_ids'=>[$items[0]],'reason'=>'Discount allocation must be explicit'],$h)->assertStatus(422);[$d]=otOrder($b,$l,$u,[[$p,'10.0000']]);$this->postJson("/api/v1/orders/$d/merge",['source_order_id'=>$a,'reason'=>'Discount merge invalid'],$h)->assertStatus(422);});
