<?php
namespace App\Services\Sales;
use App\Models\Business;use App\Models\Order;use App\Models\OrderItem;use App\Models\User;use Brick\Math\BigDecimal;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
final class OrderLifecycleService{
 private const PREPARATION_TRANSITIONS=['sent'=>['preparing'],'preparing'=>['ready'],'ready'=>['served']];public function __construct(private readonly OrderTotalsCalculator $totals){}
 public function transitionPreparation(Business$b,OrderItem$i,string$t):OrderItem{return DB::transaction(function()use($b,$i,$t){$o=$this->lockOrder($b,(string)$i->order_id);$i=$this->lockItem($b,$o,(string)$i->getKey());if(in_array($o->status,['cancelled','closed'],true))throw ValidationException::withMessages(['order'=>'Items on a cancelled or closed order cannot be changed.']);$allowed=self::PREPARATION_TRANSITIONS[$i->preparation_status]??[];if(!in_array($t,$allowed,true))throw ValidationException::withMessages(['status'=>"Cannot move an item from {$i->preparation_status} to {$t}."]);$col=match($t){'preparing'=>'preparing_at','ready'=>'prepared_at','served'=>'served_at'};$i->forceFill(['preparation_status'=>$t,$col=>now()])->save();return$i->fresh('order');},attempts:3);}
 public function voidItem(Business$b,User$u,OrderItem$i,string$r):OrderItem{return DB::transaction(function()use($b,$u,$i,$r){$o=$this->lockOrder($b,(string)$i->order_id);$i=$this->lockItem($b,$o,(string)$i->getKey());if(in_array($o->status,['paid','closed','cancelled'],true))throw ValidationException::withMessages(['item'=>'Items on a paid, closed, or cancelled order cannot be cancelled.']);if($i->preparation_status==='voided')throw ValidationException::withMessages(['item'=>'This item is already cancelled.']);if($this->hasStartedPayment($o))throw ValidationException::withMessages(['item'=>'Items cannot be cancelled after payment has started.']);$i->forceFill(['preparation_status'=>'voided','void_reason'=>trim($r),'voided_by_user_id'=>$u->getKey(),'voided_at'=>now()])->save();$this->recalculate($o);return$i->fresh('order');},attempts:3);}
 public function cancelOrder(Business$b,User$u,Order$o,string$r):Order{return DB::transaction(function()use($b,$u,$o,$r){$o=$this->lockOrder($b,(string)$o->getKey());if(in_array($o->status,['paid','closed','cancelled'],true))throw ValidationException::withMessages(['order'=>'A paid, closed, or already cancelled order cannot be cancelled.']);if($this->hasStartedPayment($o))throw ValidationException::withMessages(['order'=>'An order cannot be cancelled after payment has started. Resolve or void the active payment attempt first.']);if($this->netPaid($o)->isPositive())throw ValidationException::withMessages(['order'=>'An order with a remaining paid balance must be fully refunded before it can be cancelled.']);$now=now();$o->items()->where('preparation_status','!=','voided')->lockForUpdate()->get();$o->items()->where('preparation_status','!=','voided')->update(['preparation_status'=>'voided','void_reason'=>'Order cancelled: '.trim($r),'voided_by_user_id'=>$u->getKey(),'voided_at'=>$now,'updated_at'=>$now]);$o->forceFill(['status'=>'cancelled','cancel_reason'=>trim($r),'cancelled_by_user_id'=>$u->getKey(),'cancelled_at'=>$now])->save();return$o->fresh('items');},attempts:3);}
 private function lockOrder(Business$b,string$id):Order{return Order::query()->forBusiness($b)->whereKey($id)->lockForUpdate()->firstOrFail();}private function lockItem(Business$b,Order$o,string$id):OrderItem{return OrderItem::query()->forBusiness($b)->where('order_id',$o->getKey())->whereKey($id)->lockForUpdate()->firstOrFail();}private function hasStartedPayment(Order$o):bool{return$o->payments()->whereNotIn('status',['failed','cancelled','voided'])->exists();}
 private function netPaid(Order$o):BigDecimal{$paid=BigDecimal::of((string)$o->payments()->where('status','completed')->sum('amount_base'));$ref=BigDecimal::of((string)DB::table('payment_refunds')->join('payments','payments.id','=','payment_refunds.payment_id')->where('payments.order_id',$o->getKey())->where('payments.business_id',$o->business_id)->where('payment_refunds.status','completed')->sum('payment_refunds.amount_base'));return$paid->minus($ref);}
 private function recalculate(Order$o):void{$items=$o->items()->where('preparation_status','!=','voided')->get();if($items->isEmpty()){if(BigDecimal::of((string)$o->discount_total)->isPositive())throw ValidationException::withMessages(['order'=>'Remove the order discount before cancelling the final active item.']);$o->forceFill(['subtotal'=>'0.0000','tax_total'=>'0.0000','grand_total'=>'0.0000'])->save();return;}$c=$this->totals->calculate($items->map(fn(OrderItem$i)=>['quantity'=>(string)$i->quantity,'unit_price'=>(string)$i->unit_price,'tax_rate'=>(string)$i->tax_rate])->all());$discount=BigDecimal::of((string)$o->discount_total);$gross=BigDecimal::of($c['grand_total']);if($discount->isGreaterThan($gross))throw ValidationException::withMessages(['order'=>'Existing discount exceeds the order total after item cancellation.']);$o->forceFill(['subtotal'=>$c['subtotal'],'tax_total'=>$c['tax_total'],'grand_total'=>(string)$gross->minus($discount)])->save();}
}
