import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Boxes, FileText, PackagePlus, ReceiptText, Settings2, Users, WalletCards } from 'lucide-react';
import { api } from '../../lib/api';
import { useAuth } from '../../features/auth/AuthProvider';

type Product={id:string;name:string;sku:string|null;category_name:string|null;sale_price:string;tax_rate:string;tracks_stock:boolean;is_active:boolean};
type Stock={id:string;name:string;sku:string|null;quantity_on_hand:string;reorder_level:string};
type Expense={id:string;category:string;description:string;amount:string;currency:string;expense_date:string};
type Invoice={id:string;number:string;status:string;currency:string;grand_total:string;customer_name:string|null;issued_at:string|null};
type Staff={id:number;name:string;email:string;status:string;role_id:string|null;role_name:string|null};
type Role={id:string;name:string;slug:string};

function Heading({eyebrow,title,description,icon:Icon}:{eyebrow:string;title:string;description:string;icon:any}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="management-heading-icon"><Icon size={20}/></div></div>}
function Loading(){return <div className="panel management-state">Loading workspace data…</div>}
function ErrorState(){return <div className="panel management-state error"><AlertTriangle size={20}/> We could not load this module. Check your access and try again.</div>}
function Empty({children}:{children:string}){return <div className="management-empty">{children}</div>}
function money(value:string|number,currency='EUR'){return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(Number(value||0))}

export function ProductsPage(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['management-products'],queryFn:()=>api.get<{data:Product[]}>('/management/products').then(r=>r.data.data)});
 const toggle=useMutation({mutationFn:(p:Product)=>api.post('/management/products',{id:p.id,name:p.name,category_id:null,sku:p.sku,sale_price:p.sale_price,tax_rate:p.tax_rate,preparation_station:null,tracks_stock:Boolean(p.tracks_stock),is_active:!p.is_active}),onSuccess:()=>qc.invalidateQueries({queryKey:['management-products']})});
 if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const rows=q.data??[];
 return <><Heading eyebrow="CATALOG" title="Menu & Products" description="Control what your team can sell, price and track across the workspace." icon={ReceiptText}/><div className="metric-grid management-metrics"><div className="metric-card"><span>Products</span><strong>{rows.length}</strong><small>Total catalog</small></div><div className="metric-card"><span>Active</span><strong>{rows.filter(x=>x.is_active).length}</strong><small>Available for service</small></div><div className="metric-card"><span>Stock tracked</span><strong>{rows.filter(x=>x.tracks_stock).length}</strong><small>Inventory linked</small></div></div><div className="panel management-panel"><div className="panel-heading"><div><h2>Product catalog</h2><p>Tenant-scoped products and operational status.</p></div></div>{rows.length===0?<Empty>No products yet. Add catalog data before opening service.</Empty>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>SKU</th><th>Price</th><th>Tax</th><th>Status</th><th/></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category_name??'Uncategorized'}</td><td>{p.sku??'—'}</td><td>{money(p.sale_price)}</td><td>{Number(p.tax_rate)}%</td><td><span className={`status-badge ${p.is_active?'success':'muted'}`}>{p.is_active?'Active':'Inactive'}</span></td><td><button className="secondary-button" disabled={toggle.isPending} onClick={()=>toggle.mutate(p)}>{p.is_active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}</div></>
}

export function InventoryPage(){
 const {activeLocation}=useAuth(); const qc=useQueryClient(); const q=useQuery({queryKey:['inventory',activeLocation?.id],enabled:!!activeLocation,queryFn:()=>api.get<{data:Stock[]}>('/inventory',{params:{location_id:activeLocation!.id}}).then(r=>r.data.data)});
 const adjust=useMutation({mutationFn:({id,delta}:{id:string;delta:number})=>api.post('/inventory/adjustments',{location_id:activeLocation!.id,product_id:id,quantity_delta:delta,note:'Manual management adjustment'}),onSuccess:()=>qc.invalidateQueries({queryKey:['inventory',activeLocation?.id]})});
 if(!activeLocation)return <ErrorState/>; if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const rows=q.data??[]; const low=rows.filter(x=>Number(x.quantity_on_hand)<=Number(x.reorder_level));
 return <><Heading eyebrow="STOCK CONTROL" title="Inventory" description={`Live stock position for ${activeLocation.name}. Every adjustment is written to the inventory ledger.`} icon={Boxes}/><div className="metric-grid management-metrics"><div className="metric-card"><span>Tracked items</span><strong>{rows.length}</strong></div><div className="metric-card"><span>Low stock</span><strong>{low.length}</strong><small>At or below reorder level</small></div></div><div className="panel management-panel">{rows.length===0?<Empty>No stock-tracked products are configured.</Empty>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>SKU</th><th>On hand</th><th>Reorder</th><th>Quick adjustment</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.sku??'—'}</td><td>{s.quantity_on_hand}</td><td>{s.reorder_level}</td><td className="inline-actions"><button className="secondary-button" onClick={()=>adjust.mutate({id:s.id,delta:-1})}>−1</button><button className="secondary-button" onClick={()=>adjust.mutate({id:s.id,delta:1})}>+1</button><button className="secondary-button" onClick={()=>adjust.mutate({id:s.id,delta:10})}><PackagePlus size={15}/> +10</button></td></tr>)}</tbody></table></div>}</div></>
}

export function FinancePage(){
 const {activeBusiness}=useAuth(); const q=useQuery({queryKey:['finance'],queryFn:()=>api.get<{data:{sales:string;expenses:string;net:string;recent_expenses:Expense[]}}>('/finance/overview').then(r=>r.data.data)});
 if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const d=q.data!; const c=activeBusiness?.currency??'EUR';
 return <><Heading eyebrow="FINANCIAL CONTROL" title="Finance" description="Current-month operational sales, posted expenses and net position." icon={WalletCards}/><div className="metric-grid management-metrics"><div className="metric-card"><span>Sales</span><strong>{money(d.sales,c)}</strong><small>Completed payments</small></div><div className="metric-card"><span>Expenses</span><strong>{money(d.expenses,c)}</strong><small>Posted this month</small></div><div className="metric-card"><span>Net</span><strong>{money(d.net,c)}</strong><small>Sales less expenses</small></div></div><div className="panel management-panel"><div className="panel-heading"><div><h2>Recent expenses</h2><p>Operational expense journal.</p></div></div>{d.recent_expenses.length===0?<Empty>No expenses have been posted.</Empty>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th></tr></thead><tbody>{d.recent_expenses.map(e=><tr key={e.id}><td>{e.expense_date}</td><td>{e.category}</td><td>{e.description}</td><td><strong>{money(e.amount,e.currency)}</strong></td></tr>)}</tbody></table></div>}</div></>
}

export function InvoicesPage(){
 const q=useQuery({queryKey:['invoices'],queryFn:()=>api.get<{data:Invoice[]}>('/invoices').then(r=>r.data.data)}); if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const rows=q.data??[];
 return <><Heading eyebrow="DOCUMENTS" title="Invoices" description="Immutable commercial documents issued from tenant-owned orders. Fiscalization remains a separate integration boundary." icon={FileText}/><div className="panel management-panel">{rows.length===0?<Empty>No invoices have been issued yet.</Empty>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Issued</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><strong>{i.number}</strong></td><td>{i.customer_name??'Walk-in customer'}</td><td>{i.issued_at?new Date(i.issued_at).toLocaleString():'—'}</td><td>{money(i.grand_total,i.currency)}</td><td><span className="status-badge success">{i.status}</span></td></tr>)}</tbody></table></div>}</div></>
}

export function StaffPage(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['staff'],queryFn:()=>api.get<{data:{staff:Staff[];roles:Role[]}}>('/staff').then(r=>r.data.data)});
 const update=useMutation({mutationFn:({member,role_id}:{member:Staff;role_id:string})=>api.patch(`/staff/${member.id}`,{role_id,status:member.status}),onSuccess:()=>qc.invalidateQueries({queryKey:['staff']})}); if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const d=q.data!;
 return <><Heading eyebrow="ACCESS CONTROL" title="Staff & Roles" description="Business-scoped membership and RBAC. Global role templates are never assigned directly." icon={Users}/><div className="panel management-panel"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Staff member</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{d.staff.map(m=><tr key={m.id}><td><strong>{m.name}</strong></td><td>{m.email}</td><td><select className="table-select" value={m.role_id??''} onChange={e=>update.mutate({member:m,role_id:e.target.value})}>{d.roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></td><td><span className={`status-badge ${m.status==='active'?'success':'muted'}`}>{m.status}</span></td></tr>)}</tbody></table></div></div></>
}

export function SettingsPage(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['settings'],queryFn:()=>api.get<{data:{business:{name:string;legal_name:string|null;tax_number:string|null;currency:string;timezone:string};settings:Record<string,unknown>}}>('/settings').then(r=>r.data.data)});
 const save=useMutation({mutationFn:(data:any)=>api.put('/settings',data),onSuccess:()=>qc.invalidateQueries({queryKey:['settings']})}); if(q.isLoading)return <Loading/>; if(q.isError)return <ErrorState/>; const d=q.data!;
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({receipt_footer:String(f.get('receipt_footer')??''),service_charge_enabled:f.get('service_charge_enabled')==='on',low_stock_alerts:f.get('low_stock_alerts')==='on'})};
 return <><Heading eyebrow="WORKSPACE" title="Settings" description="Business identity and operational preferences for this tenant." icon={Settings2}/><div className="settings-grid"><div className="panel management-panel"><h2>Business profile</h2><dl className="detail-list"><div><dt>Name</dt><dd>{d.business.name}</dd></div><div><dt>Legal name</dt><dd>{d.business.legal_name??'—'}</dd></div><div><dt>Tax number</dt><dd>{d.business.tax_number??'—'}</dd></div><div><dt>Currency</dt><dd>{d.business.currency}</dd></div><div><dt>Timezone</dt><dd>{d.business.timezone}</dd></div></dl></div><form className="panel management-panel settings-form" onSubmit={submit}><h2>Operations</h2><label>Receipt footer<textarea name="receipt_footer" defaultValue={String(d.settings.receipt_footer??'')}/></label><label className="check-row"><input type="checkbox" name="service_charge_enabled" defaultChecked={Boolean(d.settings.service_charge_enabled)}/> Enable service charge</label><label className="check-row"><input type="checkbox" name="low_stock_alerts" defaultChecked={d.settings.low_stock_alerts!==false}/> Enable low-stock alerts</label><button className="primary-button" disabled={save.isPending}>{save.isPending?'Saving…':'Save settings'}</button>{save.isSuccess&&<span className="save-confirmation">Settings saved.</span>}</form></div></>
}
