<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Http\Requests\Api\V1\CloseCashSessionRequest;use App\Http\Requests\Api\V1\CollectPaymentRequest;use App\Http\Requests\Api\V1\OpenCashSessionRequest;use App\Http\Requests\Api\V1\RefundPaymentRequest;use App\Http\Requests\Api\V1\StoreCashMovementRequest;use App\Models\Business;use App\Models\CashRegister;use App\Models\CashSession;use App\Models\Order;use App\Models\Payment;use App\Services\Payments\CashSessionReconciler;use App\Services\Payments\CloseCashSession;use App\Services\Payments\CollectPayment;use App\Services\Payments\OpenCashSession;use App\Services\Payments\RecordCashMovement;use App\Services\Payments\RefundPayment;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;
class PaymentController extends Controller{
 private function location(Request $r):string{$id=$r->string('location_id')->toString();abort_if($id==='',422,'Location context is required.');return $id;}
 public function registers(Request $r):JsonResponse{$l=$this->location($r);return response()->json(['data'=>CashRegister::query()->forBusiness(app(Business::class))->where('location_id',$l)->where('is_active',true)->with('location')->orderBy('name')->get()]);}
 public function currentSession(Request $r,CashSessionReconciler $x):JsonResponse{$l=$this->location($r);$s=CashSession::query()->forBusiness(app(Business::class))->where('location_id',$l)->where('status','open')->with('register')->latest('opened_at')->first();return response()->json(['data'=>$s?[...$s->toArray(),'expected_cash_live'=>$x->expectedCash($s)]:null]);}
 public function openSession(OpenCashSessionRequest $r,OpenCashSession $s):JsonResponse{$p=$r->validated();$p['location_id']=$this->location($r);return response()->json(['data'=>$s->execute(app(Business::class),$r->user(),$p)->load('register')],201);}
 public function movement(StoreCashMovementRequest $r,string $session,RecordCashMovement $s):JsonResponse{$l=$this->location($r);$x=CashSession::query()->forBusiness(app(Business::class))->where('location_id',$l)->whereKey($session)->firstOrFail();return response()->json(['data'=>$s->execute(app(Business::class),$r->user(),$x,$r->validated())],201);}
 public function closeSession(CloseCashSessionRequest $r,string $session,CloseCashSession $s):JsonResponse{$l=$this->location($r);$x=CashSession::query()->forBusiness(app(Business::class))->where('location_id',$l)->whereKey($session)->firstOrFail();return response()->json(['data'=>$s->execute(app(Business::class),$r->user(),$x,$r->validated())]);}
 public function collect(CollectPaymentRequest $r,string $order,CollectPayment $s):JsonResponse{$l=$this->location($r);$x=Order::query()->forBusiness(app(Business::class))->where('location_id',$l)->whereKey($order)->firstOrFail();return response()->json(['data'=>$s->execute(app(Business::class),$r->user(),$x,$r->validated())],201);}
 public function refund(RefundPaymentRequest $r,string $payment,RefundPayment $s):JsonResponse{$l=$this->location($r);$x=Payment::query()->forBusiness(app(Business::class))->with('order')->whereHas('order',fn($q)=>$q->where('location_id',$l))->whereKey($payment)->firstOrFail();return response()->json(['data'=>$s->execute(app(Business::class),$r->user(),$x,$r->validated())],201);}
}
