import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';import { api,getActiveLocationId } from '../../lib/api';import type{CashRegister,CashSession,CollectPaymentInput,Payment,PaymentRefund}from'./types';
const location=()=>getActiveLocationId();const params=()=>({location_id:location()});
export function useCashRegisters(){const l=location();return useQuery({queryKey:['cash-registers',l],enabled:Boolean(l),queryFn:async()=>(await api.get<{data:CashRegister[]}>('/cash-registers',{params:{location_id:l}})).data.data});}
export function useCurrentCashSession(){const l=location();return useQuery({queryKey:['cash-session','current',l],enabled:Boolean(l),queryFn:async()=>(await api.get<{data:CashSession|null}>('/cash-sessions/current',{params:{location_id:l}})).data.data});}
export function useOpenCashSession(){const q=useQueryClient();return useMutation({mutationFn:async(input:{cash_register_id:string;opening_cash:number})=>(await api.post<{data:CashSession}>('/cash-sessions',input,{params:params()})).data.data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCashMovement(id?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{type:'cash_in'|'cash_out';amount:number;currency:string;reason:string})=>(await api.post(`/cash-sessions/${id}/movements`,input,{params:params()})).data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCloseCashSession(id?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{counted_cash:number;closing_note?:string})=>(await api.post<{data:CashSession}>(`/cash-sessions/${id}/close`,input,{params:params()})).data.data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCollectPayment(orderId?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:CollectPaymentInput)=>(await api.post<{data:Payment}>(`/orders/${orderId}/payments`,input,{params:params()})).data.data,onSuccess:()=>{q.invalidateQueries({queryKey:['orders']});q.invalidateQueries({queryKey:['cash-session']});}});}
export function useRefundPayment(paymentId?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{amount:number;reason:string;cash_session_id?:string;idempotency_key:string})=>(await api.post<{data:PaymentRefund}>(`/payments/${paymentId}/refunds`,input,{params:params()})).data.data,onSuccess:()=>{q.invalidateQueries({queryKey:['orders']});q.invalidateQueries({queryKey:['cash-session']});}});}
