import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import type { CashRegister,CashSession,CollectPaymentInput,Payment,PaymentRefund } from './types';
export function useCashRegisters(){return useQuery({queryKey:['cash-registers'],queryFn:async()=>(await api.get<{data:CashRegister[]}>('/cash-registers')).data.data});}
export function useCurrentCashSession(){return useQuery({queryKey:['cash-session','current'],queryFn:async()=>(await api.get<{data:CashSession|null}>('/cash-sessions/current')).data.data});}
export function useOpenCashSession(){const q=useQueryClient();return useMutation({mutationFn:async(input:{cash_register_id:string;opening_cash:number})=>(await api.post<{data:CashSession}>('/cash-sessions',input)).data.data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCashMovement(id?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{type:'cash_in'|'cash_out';amount:number;currency:string;reason:string})=>(await api.post(`/cash-sessions/${id}/movements`,input)).data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCloseCashSession(id?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{counted_cash:number;closing_note?:string})=>(await api.post<{data:CashSession}>(`/cash-sessions/${id}/close`,input)).data.data,onSuccess:()=>q.invalidateQueries({queryKey:['cash-session']})});}
export function useCollectPayment(orderId?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:CollectPaymentInput)=>(await api.post<{data:Payment}>(`/orders/${orderId}/payments`,input)).data.data,onSuccess:()=>{q.invalidateQueries({queryKey:['orders']});q.invalidateQueries({queryKey:['cash-session']});}});}
export function useRefundPayment(paymentId?:string){const q=useQueryClient();return useMutation({mutationFn:async(input:{amount:number;reason:string;cash_session_id?:string;idempotency_key:string})=>(await api.post<{data:PaymentRefund}>(`/payments/${paymentId}/refunds`,input)).data.data,onSuccess:()=>{q.invalidateQueries({queryKey:['orders']});q.invalidateQueries({queryKey:['cash-session']});}});}
