import { AlertTriangle, ArrowDownToLine, ArrowUpFromLine, LockKeyhole, RefreshCw, WalletCards } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useCashMovement, useCashRegisters, useCloseCashSession, useOpenCashSession, useOpenCashSessions } from '../../features/payments/api';
import type { Currency } from '../../features/payments/types';
import { useAuth } from '../../features/auth/AuthProvider';

const DENOMINATIONS: Record<Currency, number[]> = {
  ALL: [5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5],
  EUR: [500, 200, 100, 50, 20, 10, 5, 2, 1, .5, .2, .1, .05, .02, .01],
  USD: [100, 50, 20, 10, 5, 2, 1, .5, .25, .1, .05, .01],
  GBP: [50, 20, 10, 5, 2, 1, .5, .2, .1, .05, .02, .01],
};
const money=(value:number,currency:Currency)=>new Intl.NumberFormat(undefined,{style:'currency',currency,minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
const apiMessage=(error:any)=>error?.response?.data?.message??Object.values(error?.response?.data?.errors??{}).flat()[0]??'The request could not be completed.';

export function CashRegisterPage() {
  const {can}=useAuth();
  const registers = useCashRegisters(); const sessions = useOpenCashSessions(); const open = useOpenCashSession();
  const [selectedSessionId,setSelectedSessionId]=useState('');
  useEffect(()=>{const rows=sessions.data??[];setSelectedSessionId(current=>rows.some(s=>s.id===current)?current:rows[0]?.id??'')},[sessions.data]);
  const current=(sessions.data??[]).find(s=>s.id===selectedSessionId)??sessions.data?.[0];
  const movement = useCashMovement(current?.id); const close = useCloseCashSession(current?.id);
  const [registerId,setRegisterId]=useState(''); const [openingCash,setOpeningCash]=useState('0');
  const [movementType,setMovementType]=useState<'cash_in'|'cash_out'>('cash_in'); const [movementAmount,setMovementAmount]=useState('');
  const [movementCurrency,setMovementCurrency]=useState<Currency>('EUR'); const [reason,setReason]=useState('');
  const [counts,setCounts]=useState<Record<string,number>>({}); const [closingNote,setClosingNote]=useState(''); const [confirmClose,setConfirmClose]=useState(false);

  const baseCurrency=current?.base_currency??'EUR'; const denominations=DENOMINATIONS[baseCurrency]; const canClose=can('cash_sessions.close');
  useEffect(()=>{setMovementCurrency(baseCurrency)},[baseCurrency]);
  const countedCash=useMemo(()=>denominations.reduce((sum,d)=>sum+d*(counts[String(d)]??0),0),[counts,denominations]);
  if(sessions.isLoading||registers.isLoading)return <div className="page-state">Loading cash register…</div>;
  if(sessions.isError||registers.isError)return <div className="panel management-state error"><AlertTriangle size={20}/><div><strong>Cash register unavailable</strong><span>Register and session data could not be loaded.</span></div><button type="button" className="secondary-button" onClick={()=>{void Promise.all([sessions.refetch(),registers.refetch()])}}><RefreshCw size={15}/> Try again</button></div>;

  if(!current){const opening=Number(openingCash);const valid=Number.isFinite(opening)&&opening>=0;return <main className="management-page"><header className="page-heading"><div><span className="eyebrow">CASH CONTROL</span><h1>Open register shift</h1><p>Verify the opening float before the first cash transaction.</p></div><div className="management-heading-icon"><WalletCards size={20}/></div></header>{can('cash_sessions.open')?<section className="panel form-panel cash-open-panel"><label><span>Register</span><select value={registerId} onChange={e=>setRegisterId(e.target.value)}><option value="">Select register</option>{registers.data?.map(r=><option key={r.id} value={r.id}>{r.name} · {r.code}</option>)}</select></label><label><span>Opening cash</span><input type="number" min="0" step="0.01" inputMode="decimal" value={openingCash} onChange={e=>setOpeningCash(e.target.value)}/></label>{open.isError&&<p className="error-state">{String(apiMessage(open.error))}</p>}<button type="button" className="primary-action" disabled={!registerId||!valid||open.isPending} onClick={()=>open.mutate({cash_register_id:registerId,opening_cash:opening})}>{open.isPending?'Opening shift…':'Open shift'}</button></section>:<section className="panel management-state"><LockKeyhole size={20}/> No register shift is open, and your role cannot open one.</section>}</main>}

  const expected=Number(current.expected_cash_live??current.opening_cash); const difference=countedCash-expected; const hasVariance=Math.abs(difference)>=.005; const closureReady=!hasVariance||closingNote.trim().length>=3;
  const movementValue=Number(movementAmount); const movementValid=Number.isFinite(movementValue)&&movementValue>0&&reason.trim().length>=3;
  return <main className="management-page"><header className="page-heading"><div><span className="eyebrow">CASH CONTROL</span><h1>Register shift open</h1><p>Ledger-backed cash control. Physical drawer movements and reconciliation stay in {baseCurrency}.</p></div><div className="cash-session-selector">{(sessions.data??[]).length>1&&<label><span>Active drawer</span><select value={current.id} onChange={e=>{setSelectedSessionId(e.target.value);setCounts({});setClosingNote('');setConfirmClose(false)}}>{(sessions.data??[]).map(s=><option key={s.id} value={s.id}>{s.register?.name??'Register'} · {s.register?.code??s.cash_register_id}</option>)}</select></label>}<span className="status-pill success">OPEN</span></div></header>
    <section className="metric-grid"><article className="metric-card"><span>Opening float</span><strong>{money(Number(current.opening_cash),baseCurrency)}</strong></article><article className="metric-card"><span>Expected now</span><strong>{money(expected,baseCurrency)}</strong></article><article className="metric-card"><span>Counted</span><strong>{canClose?money(countedCash,baseCurrency):'—'}</strong></article><article className="metric-card"><span>Variance</span><strong>{canClose?money(difference,baseCurrency):'—'}</strong><small>{canClose?(Math.abs(difference)<.005?'Balanced':difference>0?'Cash over':'Cash short'):'Closing access required'}</small></article></section>
    <div className="two-column-layout"><section className="panel"><div className="panel-heading"><div><h2>Cash movement</h2><p>Record non-sale money entering or leaving the drawer.</p></div></div><div className="segmented-control"><button type="button" disabled={!can('cash_movements.create')} className={movementType==='cash_in'?'active':''} aria-pressed={movementType==='cash_in'} onClick={()=>setMovementType('cash_in')}><ArrowDownToLine size={15}/> Cash in</button><button type="button" disabled={!can('cash_movements.create')} className={movementType==='cash_out'?'active':''} aria-pressed={movementType==='cash_out'} onClick={()=>setMovementType('cash_out')}><ArrowUpFromLine size={15}/> Cash out</button></div><label><span>Currency</span><select disabled value={movementCurrency}><option>{baseCurrency}</option></select><small>Physical drawer movements are reconciled only in the base currency.</small></label><label><span>Amount</span><input disabled={!can('cash_movements.create')} type="number" min="0.01" step="0.01" inputMode="decimal" value={movementAmount} onChange={e=>setMovementAmount(e.target.value)}/></label><label><span>Reason</span><input disabled={!can('cash_movements.create')} maxLength={255} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Supplier payment, petty cash, extra float…"/></label>{movement.isError&&<p className="error-state">{String(apiMessage(movement.error))}</p>}<button type="button" className="secondary-action" disabled={!can('cash_movements.create')||!movementValid||movement.isPending} onClick={()=>movement.mutate({type:movementType,amount:movementValue,currency:movementCurrency,reason:reason.trim()},{onSuccess:()=>{setMovementAmount('');setReason('')}})}>{movement.isPending?'Recording…':'Record movement'}</button></section>
    <section className="panel"><div className="panel-heading"><div><h2>Close shift · physical count</h2><p>Count the physical drawer in the session base currency: <strong>{baseCurrency}</strong>.</p></div><LockKeyhole size={18}/></div><div className="denomination-grid">{denominations.map(d=><label key={d}><span>{money(d,baseCurrency)}</span><input disabled={!canClose} type="number" min="0" step="1" inputMode="numeric" value={counts[String(d)]??''} onChange={e=>setCounts({...counts,[String(d)]:Math.max(0,Math.floor(Number(e.target.value)||0))})}/></label>)}</div><label><span>Closing note {hasVariance&&<b>· required for variance</b>}</span><textarea disabled={!canClose} minLength={hasVariance?3:undefined} maxLength={1000} value={closingNote} onChange={e=>setClosingNote(e.target.value)} placeholder="Optional reconciliation note"/></label><div className="reconciliation-summary"><span>Expected <strong>{money(expected,baseCurrency)}</strong></span><span>Counted <strong>{canClose?money(countedCash,baseCurrency):'—'}</strong></span><span>Difference <strong>{canClose?money(difference,baseCurrency):'—'}</strong></span></div>{canClose&&hasVariance&&!closureReady&&<p className="field-hint error">Explain the cash variance before closing the shift.</p>}{close.isError&&<p className="error-state">{String(apiMessage(close.error))}</p>}{!canClose?<p className="field-hint">Your role can view this reconciliation but cannot close the shift.</p>:!confirmClose?<button type="button" className="danger-action" onClick={()=>setConfirmClose(true)}>Review shift closure</button>:<div className="close-confirmation"><div><AlertTriangle size={18}/><span><strong>Close this shift?</strong><small>This finalizes the cash reconciliation and cannot be used for new cash payments.</small></span></div><div className="inline-actions"><button type="button" className="secondary-button" disabled={close.isPending} onClick={()=>setConfirmClose(false)}>Keep shift open</button><button type="button" className="danger-action" disabled={close.isPending||!closureReady} onClick={()=>close.mutate({counted_cash:Number(countedCash.toFixed(2)),closing_note:closingNote.trim()||undefined},{onSuccess:()=>{setCounts({});setClosingNote('');setConfirmClose(false)}})}>{close.isPending?'Closing…':'Confirm close & reconcile'}</button></div></div>}</section></div>
  </main>;
}
